FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g turbo
COPY . .
RUN turbo prune --scope=api --docker

FROM node:20-alpine AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm install
COPY --from=builder /app/out/full/ .
RUN npx turbo run build --filter=api

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=installer /app .
CMD ["node", "apps/api/dist/server.js"]
